name: Update Userscript

on:
  push:
    branches: [ main ]
    paths:
      - 'BM-User-Overlay.js'
      - 'admins.json'
  workflow_dispatch:

jobs:
  update-userscript:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Update version and create release
      run: |
        # Get current version from userscript
        CURRENT_VERSION=$(grep -o '@version [0-9.]*' "BM-User-Overlay.js" | cut -d' ' -f2)
        echo "Current version: $CURRENT_VERSION"
        
        # Increment patch version
        IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
        NEW_PATCH=$((VERSION_PARTS[2] + 1))
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH"
        echo "New version: $NEW_VERSION"
        
        # Update version in userscript
        sed -i "s/@version $CURRENT_VERSION/@version $NEW_VERSION/" "BM-User-Overlay.js"
        
        # Update timestamp in admins.json
        CURRENT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        sed -i "s/\"updatedAt\": \"[^\"]*\"/\"updatedAt\": \"$CURRENT_DATE\"/" "admins.json"
        
        # Commit and push changes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "BM-User-Overlay.js" "admins.json"
        git commit -m "Auto-update version to $NEW_VERSION and timestamp"
        git push
        
        # Create a release
        gh release create "v$NEW_VERSION" \
          "BM-User-Overlay.js" \
          "admins.json" \
          --title "Release v$NEW_VERSION" \
          --notes "Auto-generated release for version $NEW_VERSION"
          
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.new_version }}
        release_name: Release v${{ steps.version.outputs.new_version }}
        body: |
          Auto-generated release for version ${{ steps.version.outputs.new_version }}
          
          ## Changes
          - Updated userscript version
          - Updated admin list timestamp
          
          ## Files
          - `BM-User-Overlay.js` - Updated userscript
          - `admins.json` - Updated admin list
        draft: false
        prerelease: false
